services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - MCP_HTTP_HOST=0.0.0.0
      - MCP_HTTP_PORT=3000
      - TRADING212_POOL_SIZE=16
      - TRADING212_TIMEOUT_SECS=30
    # Resource limits for production-like testing
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    # Security options
    security_opt:
      - no-new-privileges:true
